language: objective-c
osx_image: xcode7.1

env:
  global:
    - ADB_INSTALL_TIMEOUT=10 # minutes (2 minutes by default)

addons:
#  artifacts:
#    paths: /Users/travis/build/nhpatt/liferay-screens/android/samples/test-app/build/reports/androidTests/connected/

  s3_region: "eu-west-1"

cache:
  directories:
    - $HOME/android/library/.gradle/

podfile: ios/Framework

before_install:

    #Android installation (sdk, emulator, wait & unlock)
    - export COMPONENTS=build-tools-23.0.2,android-19,android-23,extra-android-m2repository,extra-google-m2repository,sys-img-armeabi-v7a-android-19
    - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS && source ~/.android-sdk-installer/env

    #iOS installation (gem, brew & pods)
    - export LANG=en_US.UTF-8
    - gem install cocoapods
    - brew update > /dev/null
    - brew outdated xctool || brew upgrade xctool
    - env
    - locale
    - pod --version

script:
    - cd android/library/
    - ./gradlew clean
    - ./gradlew assembleDebug
    - ./gradlew assembleDebugAndroidTest
    - ./gradlew test

##    - iOS tests
    - cd ../../..
    - cd ios/Framework
    - pod install
    - ./run-tests.sh
    - cd ../..

